name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Windows Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pygame
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --windowed --name GameCollection src/game/__main__.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/GameCollection.exe
          name: Release ${{ github.ref_name }}
          body: |
            🎮 **Game Collection v${{ github.ref_name }}**

            ## 🎯 Что нового:
            - ✅ Исправлено наложение элементов интерфейса в Тетрисе
            - ✅ Перемещена секция 'Следующая' ниже управления в Тетрисе
            - ✅ Исправлено отображение символов стрелок в Арканоиде
            - ✅ Уменьшен размер шрифта инструкций в Арканоиде
            - ✅ Перемещен текст статистики выше кирпичей в Арканоиде
            - ✅ Смещены инструкции влево в главном меню

            ## 🚀 Установка:
            1. Скачайте `GameCollection.exe`
            2. Запустите файл
            3. Наслаждайтесь игрой!

            ## 🎮 Игры:
            - **🐍 Snake** - Classic snake game with growing mechanics
            - **🎯 Arkanoid** - Breakout-style game with paddle and ball physics
            - **🧩 Tetris** - Block-stacking puzzle game with line clearing
            - **👻 Pac-Man** - Maze navigation game with dots and ghosts

            ## 🔧 Технические улучшения:
            - Улучшено расположение элементов UI
            - Исправлены проблемы с отображением символов
            - Оптимизированы размеры шрифтов
            - Улучшена читаемость интерфейса
            - Добавлена безопасность API токенов

            ---
            *Собрано автоматически с помощью GitHub Actions*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    name: Build Linux Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pygame
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --name GameCollection src/game/__main__.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/GameCollection
          name: Release ${{ github.ref_name }}
          body: |
            🎮 **Game Collection v${{ github.ref_name }}**

            ## 🎯 Что нового:
            - ✅ Исправлено наложение элементов интерфейса в Тетрисе
            - ✅ Перемещена секция 'Следующая' ниже управления в Тетрисе
            - ✅ Исправлено отображение символов стрелок в Арканоиде
            - ✅ Уменьшен размер шрифта инструкций в Арканоиде
            - ✅ Перемещен текст статистики выше кирпичей в Арканоиде
            - ✅ Смещены инструкции влево в главном меню

            ## 🚀 Установка:
            1. Скачайте `GameCollection`
            2. Сделайте файл исполняемым: `chmod +x GameCollection`
            3. Запустите: `./GameCollection`

            ## 🎮 Игры:
            - **🐍 Snake** - Classic snake game with growing mechanics
            - **🎯 Arkanoid** - Breakout-style game with paddle and ball physics
            - **🧩 Tetris** - Block-stacking puzzle game with line clearing
            - **👻 Pac-Man** - Maze navigation game with dots and ghosts

            ## 🔧 Технические улучшения:
            - Улучшено расположение элементов UI
            - Исправлены проблемы с отображением символов
            - Оптимизированы размеры шрифтов
            - Улучшена читаемость интерфейса
            - Добавлена безопасность API токенов

            ---
            *Собрано автоматически с помощью GitHub Actions*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
